version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.27
    restart: unless-stopped
    env_file: ./.env.example
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: ./api
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file: ./.env.example
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON:
        '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
          "spring.datasource.username": "$MYSQLDB_USER",
          "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
          "spring.flyway.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
          "spring.flyway.user": "$MYSQLDB_USER",
          "spring.flyway.password": "$MYSQLDB_ROOT_PASSWORD",
          "spring.flyway.schemas": "$MYSQLDB_DATABASE",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.database-platform": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "validate",
          "server.port": "8080"
        }'
    volumes:
      - ./api:/api
    stdin_open: true
    tty: true
volumes:
  db:
