CREATE TABLE IF NOT EXISTS movimentacao (
  id BIGINT NOT NULL AUTO_INCREMENT,
  valor DECIMAL(12, 2) NOT NULL,
  dt_hora DATETIME NOT NULL,
  tipo ENUM('SAQUE', 'DEPOSITO') NOT NULL,
  num_conta BIGINT NOT NULL,
  CONSTRAINT MOVIMENTACAO_PK PRIMARY KEY(id),
  CONSTRAINT MOVIMENTACAO_CONTA FOREIGN KEY(num_conta) REFERENCES conta(num_conta)
) engine = innoDB AUTO_INCREMENT = 1;
