CREATE TABLE IF NOT EXISTS CONTA (
  num_conta INT NOT NULL AUTO_INCREMENT,
  agencia INT NOT NULL,
  saldo DECIMAL(12, 2) NOT NULL DEFAULT 0,
  dt_abertura DATE NOT NULL,
  dt_encerramento DATE,
  cpf VARCHAR(11) NOT NULL,
  CONSTRAINT CONTA_PK PRIMARY KEY(num_conta),
  CONSTRAINT CONTA_CLIENTE_FK FOREIGN KEY(cpf) REFERENCES CLIENTE(cpf)
) engine = innoDB AUTO_INCREMENT = 1;
