CREATE TABLE IF NOT EXISTS MOVIMENTACAO (
  id INT NOT NULL AUTO_INCREMENT,
  valor DECIMAL(12, 2) NOT NULL,
  dt_hora DATETIME NOT NULL,
  tipo ENUM('saque', 'deposito') NOT NULL,
  num_conta INT NOT NULL,
  CONSTRAINT MOVIMENTACAO_PK PRIMARY KEY(id),
  CONSTRAINT MOVIMENTACAO_CONTA FOREIGN KEY(num_conta) REFERENCES CONTA(num_conta)
) engine = innoDB AUTO_INCREMENT = 1;
